config/routes.rb
Rails.application.routes.draw do

  root 'pitches#index'

  get 'sort' => 'pitches#sort', as: :sort_pitches

  post '/set-session' => 'users#set_session'

  resources :sessions, only: [:new, :destroy, :create]
  resources :users
  resources :comments, only: [:new, :create, :destroy]
  resources :subcomments, only: [:new, :create, :destroy]
  get "/startup_world" => 'startup_world#index'

  resources :pitches

  resources :votes, only: [:create, :update] do
    member do
      post :toggle
    end
  end

end

app/controllers/pitches_controller.rb
require 'httparty'
require 'ap'

class PitchesController < ApplicationController
  respond_to :html, :json
  before_action :set_current_user

  def index
    sort_type = params[:sort_type] || "hot"

    response = HTTParty.get('http://pitchitbackend.herokuapp.com/pitches?sort_type=' + sort_type)

    @pitches = response.parsed_response

  end

  def show
    response = HTTParty.get('http://pitchitbackend.herokuapp.com/pitches/' + params[:id])
    @pitch = response
    @pitch_comments = @pitch["comments"]

    if request.xhr?
      render text: @pitch["video"].to_json
    end


  end

  def new
    @pitch = {}
  end

  def edit
    # @pitch = Pitch.find(params[:id])
  end

  def create

    response = RestClient.post 'http://pitchitbackend.herokuapp.com/pitches', :pitch => params, :accept => :json

    response = JSON.parse(response)

    p response

    redirect_to pitch_path(response["id"])
  end

  def update
    # @pitch = Pitch.find(params[:id])

    # if @pitch.update(pitch_params)
    #   redirect_to @pitch
    # else
    #   render 'edit'
    # end
  end

  def destroy
    # @pitch = Pitch.find(params[:id])
    # @pitch.destroy

    # redirect_to pitches_path
  end

  def sort
    sort_type = params[:sort_type] || "hot"

    response = HTTParty.get('http://pitchitbackend.herokuapp.com/pitches?sort_type=' + sort_type)

    @pitches = response.parsed_response
    render partial: 'pitches/pitch_list'
  end

  private
    def set_current_user
      @current_user = get_current_user
    end

    def get_current_user
      return nil unless session[:user_id]


      current_user = RestClient.get("http://pitchitbackend.herokuapp.com/users/" + session[:user_id].to_s, :accept => :json)

      JSON.parse(current_user)
    end

    def pitch_params
      # params.require(:pitch).permit(:title,
      #   :tagline,
      #   :description,
      #   :media)
    end
    # def sort_type
    #   params.require(:sort_type)
    # end

    def set_pitch
      # @pitch = Pitch.find(params[:id])
    end
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/views/pitches/_form.html.erb
<form id="new-pitch-form" class="new_pitch" action="/pitches" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" />
  <input name="pitch[user_id]" type="hidden" value="<%= @current_user['id'] %>" >
  <div class="row">
    <div class="new-pitch field five columns">
      <input autofocus="autofocus" autocomplete="false" placeholder="title" type="text" name="pitch[title]" id="pitch_title" />
    </div>
    <div class="six columns">
      <p>
        Give your pitch a title. This could be the name of your company,
        your idea, or your own name. (50 characters max)
      </p>
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <input placeholder="tagline" type="text" name="pitch[tagline]" id="pitch_tagline" />
    </div>
    <div class="six columns">
      <p>
        Provide a tagline for your pitch. Let people know what it's all about. Be creative! (140 characters max)
      </p>
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <textarea placeholder="description" name="pitch[description]" id="pitch_description">
</textarea>
    </div>
    <div class="six columns">
      <p>
        Here, you can expand on the tagline and go in-depth about your idea.
        Say as much or as little as you'd like. Some starter ideas: motivations,
        technologies, vision. (1500 characters max)
      </p>
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns media-field">
      <input placeholder="media" type="url" name="pitch[media]" id="pitch_media" />
    </div>
    <div class="six columns">
      <p>
        If you have any media to attach (like a YouTube video), add the URL here.
      </p>
    </div>
  </div>

   <div class="new-pitch actions">
    <input type="submit" name="commit" value="Submit" />
    
  </div>


</form>

app/views/pitches/_pitch_list.html.erb
<ul class="pitch-list">
  <% @pitches.each.with_index do |pitch, index| %>
  <li class="pitch">
    <div>

      <div class="row">
        <div class="one column rank"><h4><%= index + 1 %></h4></div>
        <div class="pitch-title eight columns"><h4><a href="/pitches/<%= pitch[
        'id'] %>"><%= pitch["title"] %></a></h4></div>

      <% if pitch["media"] %>
        <div class="three columns video-button" id="<%= pitch["id"] %>">
          <%= button_to 'Show Video', pitches_path, method: :get, :class => "show-video-button u-pull-right" %>
          <%= button_to 'Hide Video', pitches_path, method: :get, :class => "hide-video-button u-pull-right", id: "hide" %>
        </div>
      <% end %>
      </div>


      <div class="row pitch-info">
        <div class="one column rank"><p>
          <i class="fa fa-chevron-up pitch-vote-up fa-2x
          <% if user_has_voted?(pitch["id"], 'Pitch') %>
            user-has-voted
           <% end %>"
           id="<%= pitch["id"] %>-vote-up"></i>
        </p></div>
        <div class="eleven columns"><%= pitch["tagline"] %></div>
      </div>


      <div class="row">
        <div id="<%= pitch["id"] %>-vote-count" class="one column pitch-vote-count"><%= pitch["vote_count"] %></div>

        <div class="eleven columns embedded video" id="<%= pitch["id"] %>-video"></div>
      </div>
      <div class="row pitch-info">
        <div class="one column rank"><p><i class='fa fa-bookmark fa-2x pitch-bookmark' id="<%= pitch["id"] %>-bookmark"></i></i></p></div>


        <div class="two columns"><%= pitch["comment_count"] %> comments</div>
        <div class="four columns"><%= pitch["created_at"] %></div>
        <div class="three columns pitch-user u-pull-right"><a href='users/<%= pitch["user_id"] %>'><%= pitch["author"] %></a></div>
      </div>
    </div>
  </li>
  <% end %>
</ul>

app/views/pitches/edit.html.erb
<h1>Edit Pitch</h1>

<%= render "form" %>

app/views/pitches/index.html.erb
<div class="main-headerr row">
  <%= image_tag "the_pitch.png", id: 'logo' %>
  <h1 id="pitch-it">itch it</h1>
  <div class="sort_type">
    <%= link_to "Hot", pitches_path(sort_type: "hot"), id: "hot" %> |
    <%= link_to "New", pitches_path(sort_type: "new"), id: "new" %> |
    <%= link_to "Top", pitches_path(sort_type: "top"), id: "top" %> |
    <%= link_to "Most Discussed", pitches_path(sort_type: "most_discussed"), id: "most_discussed" %>
  </div>
</div>

<div class="pitch_list">
  <%= render partial: 'pitch_list', locals: {pitches: @pitches} %>
</div>

app/views/pitches/new.html.erb
<h1>Make Your Pitch</h1>

<%= render "form" %>

app/views/pitches/show.html.erb
<div class="row main-header pitch-show-header">
  <div class="one column">

      <h4 title="Vote"><i class="fa fa-chevron-up
          pitch-vote-up fa-2x" id="<%= @pitch["id"] %>-vote-up"></i></h4>
      <h4 class="pitch-vote-count"><%= @pitch["vote_count"] %></h4>
      <h4 title="Bookmark"><i class='fa fa-bookmark fa-2x

          pitch-bookmark' id="<%= @pitch["id"] %>-bookmark"></i></h4>
    <% if @current_user && session[:user_id] == @pitch["user_id"] %>
      <h4><%= link_to raw("<i class='fa fa-pencil fa-2x'></i>"), edit_pitch_path(@pitch["id"]) %></h4>
      <% end %>

  </div>
</div>

<div class="row main-inner-header">
  <div class="row">
    <div class="twelve columns"><h1><%= @pitch["title"] %></h1></div>
  </div>
  <div class="row">
    <div class="twelve columns"><h5><em>"<%= @pitch["tagline"] %>"</em></h5></div>
  </div>
  <div class="row author-title">
    <div><h3><%= link_to "#{@pitch["author"]}", user_path(@pitch["user_id"]) %></h3></div>
    <div><%= @pitch["created_at"] %> </div>
  </div>
</div>

<br>

<section class="description">
  <h3>Summary</h3>
  <p><%= @pitch["description"] %></p>
</section>

<div class="media">
  <iframe width="560" height="315" src="<%= @pitch["video"] %>" frameborder="0" allowfullscreen></iframe>
</div>

<br>

<% if @current_user && session[:user_id] == @pitch["user_id"] %>
  <%= link_to "Edit Your Pitch", edit_pitch_path(@pitch["id"]) %>
<% end %>

<section id="comment-box">
  <div>
      <%= react_component 'CommentList', { pitchcomments: @pitch_comments, pitch: @pitch["id"], user_id: session[:user_id] } %>

  </div>
</section>