config/routes.rb
Rails.application.routes.draw do

  root 'pitches#index'

  get 'sort' => 'pitches#sort', as: :sort_pitches

  post '/set-session' => 'users#set_session'

  resources :sessions, only: [:new, :destroy, :create]
  resources :users
  resources :comments, only: [:new, :create, :destroy]
  resources :subcomments, only: [:new, :create, :destroy]
  get "/startup_world" => 'startup_world#index'

  resources :pitches

  resources :votes, only: [:create, :update] do
    member do
      post :toggle
    end
  end

end

app/controllers/users_controller.rb
require 'ap'
require 'json'
require "httparty"

class UsersController < ApplicationController
  before_action :set_current_user


  def show

    id = params[:id]

    response = HTTParty.get('http://pitchitbackend.herokuapp.com/users/'+id)
    @user_hash = response
  end

  def new

  end

  def create
    response = RestClient.post 'http://pitchitbackend.herokuapp.com/users', :user => params, :accept => :json

    session[:user_id] = JSON.parse(response)["id"]

    # ap @result
    redirect_to user_path(session[:user_id])
  end

  def edit

  end

  def update
    HTTParty.post('http://pitchitbackend.herokuapp.com/users/' + params[:id],
      params[:user]
    )
  end

  def set_session
    session[:user_id] = params[:id]
    render json: "Success"

  end

  private
    def set_current_user
      @current_user = get_current_user
    end

    def get_current_user
      return nil unless session[:user_id]


      current_user = RestClient.get("http://pitchitbackend.herokuapp.com/users/" + session[:user_id].to_s, :accept => :json)

      JSON.parse(current_user)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def get_current_user
    return nil unless session[:user_id]

    current_user = RestClient.get("http://pitchitbackend.herokuapp.com/users/" + session[:user_id].to_s, :accept => :json)


    JSON.parse(current_user)
  end

  def user_has_voted?(votable_id, votable_type)
    voted = false

    if get_current_user
      user_votes = get_current_user["votes"]

      user_votes.each do |vote|
        if vote["votable_type"] == votable_type && vote["votable_id"] == votable_id.to_i
          voted = true
        end
      end
    end

    voted

  end
end

app/views/users/_new.html.erb
<h2>Sign Up</h2>

<i class="fa fa-times exit-signup"></i>

<%= form_for :user, url: users_path, method: :post do |f| %>
  <%= f.text_field :first_name, placeholder: "first name" %>
  <%= f.text_field :last_name, placeholder: "last name" %>
  <%= f.text_field :email, placeholder: "email" %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>

<form id="user_form" class="edit_user" action="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="put" /><input type="hidden" name="authenticity_token" value="HcqQG/qjTnpsx8CL09vqtK/iCbtASoLf7vdnAQ7oyCgV+svPWWpXQiZspVro9jrfWPn6qT15aQExOcjvOz2TJg==" />
  

  <div class="row">
    <div class="new-pitch field five columns">
      <input autofocus="autofocus" placeholder="first name" type="text" value="Yohan" name="user[first_name]" id="user_first_name" />
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <input autofocus="autofocus" placeholder="last name" type="text" value="yolo" name="user[last_name]" id="user_last_name" />
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <input autofocus="autofocus" placeholder="email" type="email" value="y@y.com" name="user[email]" id="user_email" />
    </div>
  </div>


  <div class="row">
    <div class="new-pitch field five columns">
      <label for="user_password">Password</label> <i>(leave blank if you don't want to change it)</i><br />
      <input autocomplete="off" placeholder="password (leave blank if you don&#39;t want to change it)" type="password" name="user[password]" id="user_password" />
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <input autocomplete="off" placeholder="confirm password" type="password" name="user[password_confirmation]" id="user_password_confirmation" />
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <input autocomplete="off" placeholder="avatar url" type="url" value="" name="user[picture_url]" id="user_picture_url" />
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <input placeholder="company" type="text" value="Swag LLC" name="user[company]" id="user_company" />
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <label for="user_blurb">Blurb</label><br />
      <textarea placeholder="blurb" name="user[blurb]" id="user_blurb">
yol ocity </textarea>
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <label for="user_phone">Phone</label><br />
      <input autocomplete="off" placeholder="phone" type="tel" value="" name="user[phone]" id="user_phone" />
    </div>
  </div>

  <label for="user_user_type">User type</label>
  <div class="row">
    <div class="field one column"><input type="radio" name="user_type" id="user_type_business" value="business" /></div>
    <div class="field five columns">I'm an entrepeneur</div>
  </div>
  <div class="row">
      <div class="field one column"><input type="radio" name="user_type" id="user_type_investor" value="investor" /></div>
      <div class="field five columns">I'm interested in investing</div>
  </div>
  <div class="row">
      <div class="field one column"><input type="radio" name="user_type" id="user_type_early_adopter" value="early_adopter" /></div>
      <div class="field five columns">I'm an early adopter</div>
  </div>

  <div class="row">
    <div class="field">
      <label for="user_current_password">Current password</label> <i>(we need your current password to confirm your changes)</i><br />
      <input autocomplete="off" type="password" name="user[current_password]" id="user_current_password" />
    </div>
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="Update" />
  </div>
</form>
<h3>Cancel my account</h3>

<p>Unhappy? <a data-confirm="Are you sure?" class="button" rel="nofollow" data-method="delete" href="/users">Cancel my account</a></p>

<a href="http://localhost:9000/pitches/new">Back</a>

</div>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="row">
    <div class="new-pitch field five columns">
      <%= f.text_field :first_name, autofocus: true, placeholder: "first name" %>
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <%= f.text_field :last_name, placeholder: "last name" %>
    </div>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <%= f.email_field :email, placeholder: "email" %>
    </div>
  </div>


  <div class="row">
    <div class="new-pitch field five columns">
      <%= f.password_field :password, autocomplete: "off", placeholder: "password" %>
    </div>
      <% if @minimum_password_length %>
        <div class="three columns password-info"><em>(<%= @minimum_password_length %> characters minimum)</em></div>
      <% end %>
  </div>

  <div class="row">
    <div class="new-pitch field five columns">
      <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "confirm password" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile-header">
  <% if @user_hash["id"] == session[:user_id] %>
    <h1>Your Profile</h1>
  <% end %>

  <div class="row">
    <% if @user_hash["picture_url"] %>
      <div class="four columns avatar">
        <img src=<%= @user_hash["picture_url"] %> class="avatar-photo">
      </div>
    <% end %>
    <div class="eight columns">
      <div class="row">
        <h1><%= @user_hash["full_name"] %></h1>
        <% if @user_hash["user_type"] %>
          <h4><%= @user_hash["first_name"] %> is a <%= @user_hash["user_type"] %></h4>
        <% end %>
        <p><%= @user_hash["blurb"] || "This user does not have a blurb yet." %></p>
      </div>
    </div>
  </div>
</div>
<% if @current_user %>
  <div class="contact">
    <h4>Click for Contact Information</h4>
    <ul class="contact-list">
      <%= raw("<li>Phone: #{@user_hash["phone"]}</li>") if @user_hash["phone"] %>
      <%= raw("<li>Email: #{@user_hash["email"]}</li>") if @user_hash["email"] %>
      <%= raw("<li>Company: #{@user_hash["company"]}</li>") if @user_hash["company"] %>
    </ul>
  </div>
<% end %>

  <% if @user_hash["pitches"] && @user_hash["pitches"].length > 0 %>
    <table class="@user_hash-pitches user_table user-pitches">
      <thead>
        <td>Pitches</td>
        <td class="votes-heading">Votes</td>
      </thead>
      <% @user_hash["pitches"].each do |pitch| %>
      <tr>
        <td><p><h3><%= link_to "#{pitch["title"]}", pitch_path(pitch["id"]) %></h3><br><em><%= pitch["tagline"] %></em></p></td>
        <td class="vote-count"><%= pitch["vote_count"] %></td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>No pitches.</p>
  <% end %>

  <% if @user_hash["comments"] && @user_hash["comments"].length > 0 %>
    <table class="user-comments">
      <thead>
        <td>Comments</td>
        <td class="votes-heading">Votes</td>
      </thead>
      <% @user_hash["comments"].each do |comment| %>
      <tr>
        <td><p><%= link_to "#{comment["pitch_title"]}", pitch_path(comment["pitch_id"]) %><br><%= comment["content"] %> </p></td>
        <td class="vote-count"><%= comment["vote_count"] %></td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>No comments.</p>
  <% end %>

<% if @current_user %>
  <table class="@user_hash-bookmarks">
    <thead>
      <td>Your Bookmarks</td>
    </thead>
    <% @user_hash["votes"].select{ |vote| vote["bookmarked"] == true}.each do |vote| %>
      <tr>
        <% if vote["votable_type"] == "Pitch" %>
          <td><p><%= link_to "#{vote["votable_title"]}", pitch_path(vote["votable_id"]) %><br><em><%= vote["votable_tagline"] %></em></p></td>
        <% else %>
          <td><p><%= link_to "#{vote["votable_title"]}", pitch_path(vote["votable_parent_id"]) %><br><%= vote["votable_content"] %> </p></td>
        <% end %>
      </tr>
    <% end %>
  </div>
<% end %>