config/routes.rb
Rails.application.routes.draw do

  root 'pitches#index'

  get 'sort' => 'pitches#sort', as: :sort_pitches

  post '/set-session' => 'users#set_session'

  resources :sessions, only: [:new, :destroy, :create]
  resources :users
  resources :comments, only: [:new, :create, :destroy]
  resources :subcomments, only: [:new, :create, :destroy]
  get "/startup_world" => 'startup_world#index'

  resources :pitches

  resources :votes, only: [:create, :update] do
    member do
      post :toggle
    end
  end

end

app/views/layouts/_navbar.html.erb
<div class="row" id="nav-bar">
    <div class="one column"><%= link_to "Home", pitches_path, :class => "home-link" %></div>
    <div class="one column"><%= link_to "News", startup_world_path %></div>
  <% if session[:user_id] %>
      <div class="four columns user-welcome">Logged in as <strong><%= get_current_user["email"] %></strong></div>
      <div class="six columns u-pull-right user-links">
        <%= link_to "Make a Pitch", new_pitch_path %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "Your Profile", user_path(get_current_user["id"]) %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to 'Edit profile', edit_user_path(get_current_user["id"]), :class => 'navbar-link' %>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "Logout", session_path(get_current_user["id"]), method: :delete, :class => 'navbar-link'  %>
      </div>
    <% else %>
      <div class="one columns u-pull-right"><%= link_to "Sign up", new_user_path, :class => 'navbar-link header-signup-link'  %></div>
      <div class="one columns u-pull-right"><%= link_to "Login", new_session_path, :class => 'navbar-link header-login-link' %></div>
      <div class="nine columns u-pull-right login-form-div">
        <%= render 'sessions/new' %>
      </div>
    <% end %>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pitch It</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "the_pitch.png" %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Damion">
</head>
<body <%= "class=user-logged-in" if session[:user_id] %> <%if session[:user_id]%> id='<%= session[:user_id] %>' <% end %> >
  <div class="overlay"></div>
  <div class="sign-up-box"><%= render 'users/new' %></div>


  <header>
    <%= render 'layouts/navbar' %>
  </header>

<div class="container page-body">
  <%= yield %>
</div>

</body>
</html>